apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: mongo-auth-service
    newName: mongo-auth-service
    newTag: latest

